name: sbku_app
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  getwidget: ^7.0.0
  gradient_borders: ^1.0.0
  flutter_svg: ^2.1.6
  memory_cache: ^1.2.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  supabase_flutter: ^2.12.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - assets/images/sbku-logo.svg
    - assets/images/campus.png
